# CONSTANTS FOR THE GAME

## Screen dimensions
SCREEN_WIDTH = 640 #1280
SCREEN_HEIGHT = 360 #720

## Player properties
PLAYER_RADIUS = 20 
LINE_WIDTH = 2
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200

## Asteroid properties
ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE_SECONDS = 0.8
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

## Shooting properties
SHOT_RADIUS = 5
PLAYER_SHOT_SPEED = 500